# Generated by Django 5.1.3 on 2024-11-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0002_alter_item_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unit_price',
        ),
    ]
