# Generated by Django 5.0.3 on 2024-11-10 10:12

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compatibility',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
