# Generated by Django 5.0.3 on 2025-01-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('problem_type', models.CharField(choices=[('Sprzęt', 'Sprzęt'), ('Oprogramowanie', 'Oprogramowanie'), ('Kompatybilność', 'Kompatybilność'), ('Inny', 'Inny')], max_length=20)),
                ('problem_description', models.TextField(max_length=1000)),
            ],
        ),
    ]
