# Generated by Django 5.0.3 on 2025-01-18 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactFrom',
            new_name='ContactForm',
        ),
    ]
